import 'package:flutter/material.dart';

class AppColors {
  AppColors._();

  static final Map<String, Color> medStock = {
    'primary':               Color.fromRGBO(8, 145, 178, 1),
    'secondary':             Color.fromARGB(255, 45, 84, 116),
    'drawerHeader':          Color.fromARGB(255, 12, 65, 108),
    'themeSeed':             Colors.blueGrey,
    'textOnPrimary':         Colors.white,
    'textOnSurface':         Color(0xFF1A1A1A),
    'textSubtle':            Colors.grey,
    'cardBackground':        Color.fromARGB(255, 244, 244, 244),
    'cardBorder':            Color(0xFFE2E8F0),
    'danger':                Colors.red,
    'onDanger':              Colors.white,
    'stockBackground':       Colors.blue.shade50,
    'stockLabel':            Colors.blue.shade700,
    'stockValue':            Colors.blue.shade900,
    'priceBackground':       Colors.green.shade50,
    'priceLabel':            Colors.green.shade700,
    'priceValue':            Colors.green.shade900,
    'pageIndicatorActive':   Colors.blue,
    'pageIndicatorInactive': Colors.grey,
    'iconPrimary':           Color.fromRGBO(8, 145, 178, 1),
    'iconSubtle':            Colors.grey,
    'iconOnPrimary':         Colors.white,
    'iconDanger':            Colors.red,
  };

  static final Map<String, Color> emerald = {
    'primary':               Color(0xFF059669),
    'secondary':             Color(0xFF065F46),
    'drawerHeader':          Color(0xFF064E3B),
    'themeSeed':             Colors.green,
    'textOnPrimary':         Colors.white,
    'textOnSurface':         Color(0xFF1A1A1A),
    'textSubtle':            Colors.grey,
    'cardBackground':        Color(0xFFF0FDF4),
    'cardBorder':            Color(0xFFE2E8F0),
    'danger':                Colors.red,
    'onDanger':              Colors.white,
    'stockBackground':       Colors.green.shade50,
    'stockLabel':            Colors.green.shade700,
    'stockValue':            Colors.green.shade900,
    'priceBackground':       Colors.teal.shade50,
    'priceLabel':            Colors.teal.shade700,
    'priceValue':            Colors.teal.shade900,
    'pageIndicatorActive':   Color(0xFF059669),
    'pageIndicatorInactive': Colors.grey,
    'iconPrimary':           Color(0xFF059669),
    'iconSubtle':            Colors.grey,
    'iconOnPrimary':         Colors.white,
    'iconDanger':            Colors.red,
  };

  static final Map<String, Color> violet = {
    'primary':               Color(0xFF7C3AED),
    'secondary':             Color(0xFF4C1D95),
    'drawerHeader':          Color(0xFF3B0764),
    'themeSeed':             Colors.purple,
    'textOnPrimary':         Colors.white,
    'textOnSurface':         Color(0xFF1A1A1A),
    'textSubtle':            Colors.grey,
    'cardBackground':        Color(0xFFFAF5FF),
    'cardBorder':            Color(0xFFE2E8F0),
    'danger':                Colors.red,
    'onDanger':              Colors.white,
    'stockBackground':       Colors.purple.shade50,
    'stockLabel':            Colors.purple.shade700,
    'stockValue':            Colors.purple.shade900,
    'priceBackground':       Colors.indigo.shade50,
    'priceLabel':            Colors.indigo.shade700,
    'priceValue':            Colors.indigo.shade900,
    'pageIndicatorActive':   Color(0xFF7C3AED),
    'pageIndicatorInactive': Colors.grey,
    'iconPrimary':           Color(0xFF7C3AED),
    'iconSubtle':            Colors.grey,
    'iconOnPrimary':         Colors.white,
    'iconDanger':            Colors.red,
  };

  static final Map<String, Color> sunset = {
    'primary':               Color(0xFFEA580C),
    'secondary':             Color(0xFF9A3412),
    'drawerHeader':          Color(0xFF7C2D12),
    'themeSeed':             Colors.deepOrange,
    'textOnPrimary':         Colors.white,
    'textOnSurface':         Color(0xFF1A1A1A),
    'textSubtle':            Colors.grey,
    'cardBackground':        Color(0xFFFFF7ED),
    'cardBorder':            Color(0xFFE2E8F0),
    'danger':                Color(0xFFDC2626),
    'onDanger':              Colors.white,
    'stockBackground':       Colors.orange.shade50,
    'stockLabel':            Colors.orange.shade700,
    'stockValue':            Colors.orange.shade900,
    'priceBackground':       Colors.amber.shade50,
    'priceLabel':            Colors.amber.shade700,
    'priceValue':            Colors.amber.shade900,
    'pageIndicatorActive':   Color(0xFFEA580C),
    'pageIndicatorInactive': Colors.grey,
    'iconPrimary':           Color(0xFFEA580C),
    'iconSubtle':            Colors.grey,
    'iconOnPrimary':         Colors.white,
    'iconDanger':            Color(0xFFDC2626),
  };

  static final Map<String, Color> slate = {
    'primary':               Color(0xFF475569),
    'secondary':             Color(0xFF1E293B),
    'drawerHeader':          Color(0xFF0F172A),
    'themeSeed':             Colors.blueGrey,
    'textOnPrimary':         Colors.white,
    'textOnSurface':         Color(0xFF1A1A1A),
    'textSubtle':            Colors.grey,
    'cardBackground':        Color(0xFFF8FAFC),
    'cardBorder':            Color(0xFFE2E8F0),
    'danger':                Colors.red,
    'onDanger':              Colors.white,
    'stockBackground':       Colors.blueGrey.shade50,
    'stockLabel':            Colors.blueGrey.shade700,
    'stockValue':            Colors.blueGrey.shade900,
    'priceBackground':       Colors.teal.shade50,
    'priceLabel':            Colors.teal.shade700,
    'priceValue':            Colors.teal.shade900,
    'pageIndicatorActive':   Color(0xFF475569),
    'pageIndicatorInactive': Colors.grey,
    'iconPrimary':           Color(0xFF475569),
    'iconSubtle':            Colors.grey,
    'iconOnPrimary':         Colors.white,
    'iconDanger':            Colors.red,
  };

  static final Map<String, Color> darkOcean = {
    'primary':               Color(0xFF38BDF8),
    'secondary':             Color(0xFF0EA5E9),
    'drawerHeader':          Color(0xFF0A1628),
    'themeSeed':             Color(0xFF38BDF8),
    'textOnPrimary':         Color(0xFFEDE9FE),
    'textOnSurface':         Color(0xFFF1F5F9),
    'textSubtle':            Color(0xFF94A3B8),
    'cardBackground':        Color(0xFF243447),
    'cardBorder':            Color(0xFF334155),
    'danger':                Color(0xFFF87171),
    'onDanger':              Colors.white,
    'stockBackground':       Color(0xFF0C4A6E),
    'stockLabel':            Color(0xFF38BDF8),
    'stockValue':            Color(0xFFE0F2FE),
    'priceBackground':       Color(0xFF064E3B),
    'priceLabel':            Color(0xFF34D399),
    'priceValue':            Color(0xFFD1FAE5),
    'pageIndicatorActive':   Color(0xFF38BDF8),
    'pageIndicatorInactive': Color(0xFF334155),
    'iconPrimary':           Color(0xFF38BDF8),
    'iconSubtle':            Color(0xFF94A3B8),
    'iconOnPrimary':         Color(0xFF0F172A),
    'iconDanger':            Color(0xFFF87171),
  };

  static final Map<String, Color> darkViolet = {
    'primary':               Color(0xFFA78BFA),
    'secondary':             Color(0xFF7C3AED),
    'drawerHeader':          Color(0xFF0D0120),
    'themeSeed':             Color(0xFFA78BFA),
    'textOnPrimary':         Color(0xFFEDE9FE),
    'textOnSurface':         Color(0xFFF1F5F9),
    'textSubtle':            Color(0xFF94A3B8),
    'cardBackground':        Color(0xFF241340),
    'cardBorder':            Color(0xFF3B1F6E),
    'danger':                Color(0xFFF87171),
    'onDanger':              Colors.white,
    'stockBackground':       Color(0xFF2E1065),
    'stockLabel':            Color(0xFFA78BFA),
    'stockValue':            Color(0xFFEDE9FE),
    'priceBackground':       Color(0xFF1E1B4B),
    'priceLabel':            Color(0xFF818CF8),
    'priceValue':            Color(0xFFE0E7FF),
    'pageIndicatorActive':   Color(0xFFA78BFA),
    'pageIndicatorInactive': Color(0xFF334155),
    'iconPrimary':           Color(0xFFA78BFA),
    'iconSubtle':            Color(0xFF94A3B8),
    'iconOnPrimary':         Color(0xFF1A0533),
    'iconDanger':            Color(0xFFF87171),
  };

  static final Map<String, Color> darkEmerald = {
    'primary':               Color(0xFF34D399),
    'secondary':             Color(0xFF059669),
    'drawerHeader':          Color(0xFF011A14),
    'themeSeed':             Color(0xFF34D399),
    'textOnPrimary':         Color(0xFFEDE9FE),
    'textOnSurface':         Color(0xFFF1F5F9),
    'textSubtle':            Color(0xFF94A3B8),
    'cardBackground':        Color(0xFF112920),
    'cardBorder':            Color(0xFF1A4035),
    'danger':                Color(0xFFF87171),
    'onDanger':              Colors.white,
    'stockBackground':       Color(0xFF064E3B),
    'stockLabel':            Color(0xFF34D399),
    'stockValue':            Color(0xFFD1FAE5),
    'priceBackground':       Color(0xFF042F2E),
    'priceLabel':            Color(0xFF2DD4BF),
    'priceValue':            Color(0xFFCCFBF1),
    'pageIndicatorActive':   Color(0xFF34D399),
    'pageIndicatorInactive': Color(0xFF334155),
    'iconPrimary':           Color(0xFF34D399),
    'iconSubtle':            Color(0xFF94A3B8),
    'iconOnPrimary':         Color(0xFF022C22),
    'iconDanger':            Color(0xFFF87171),
  };

  static final Map<String, Color> darkSunset = {
    'primary':               Color(0xFFFB923C),
    'secondary':             Color(0xFFEA580C),
    'drawerHeader':          Color(0xFF0F0400),
    'themeSeed':             Color(0xFFFB923C),
    'textOnPrimary':         Color(0xFFEDE9FE),
    'textOnSurface':         Color(0xFFF1F5F9),
    'textSubtle':            Color(0xFF94A3B8),
    'cardBackground':        Color(0xFF241808),
    'cardBorder':            Color(0xFF3D2A10),
    'danger':                Color(0xFFF87171),
    'onDanger':              Colors.white,
    'stockBackground':       Color(0xFF431407),
    'stockLabel':            Color(0xFFFB923C),
    'stockValue':            Color(0xFFFFEDD5),
    'priceBackground':       Color(0xFF3D1F00),
    'priceLabel':            Color(0xFFFBBF24),
    'priceValue':            Color(0xFFFEF3C7),
    'pageIndicatorActive':   Color(0xFFFB923C),
    'pageIndicatorInactive': Color(0xFF334155),
    'iconPrimary':           Color(0xFFFB923C),
    'iconSubtle':            Color(0xFF94A3B8),
    'iconOnPrimary':         Color(0xFF1C0A00),
    'iconDanger':            Color(0xFFF87171),
  };

  static final Map<String, Color> darkRose = {
    'primary':               Color(0xFFFB7185),
    'secondary':             Color(0xFFE11D48),
    'drawerHeader':          Color(0xFF3D0020),
    'themeSeed':             Color(0xFFFB7185),
    'textOnPrimary':         Color(0xFFEDE9FE),
    'textOnSurface':         Color(0xFFF1F5F9),
    'textSubtle':            Color(0xFF94A3B8),
    'cardBackground':        Color(0xFF24101A),
    'cardBorder':            Color(0xFF4A1530),
    'danger':                Color(0xFFF87171),
    'onDanger':              Colors.white,
    'stockBackground':       Color(0xFF4C0519),
    'stockLabel':            Color(0xFFFB7185),
    'stockValue':            Color(0xFFFFE4E6),
    'priceBackground':       Color(0xFF3D0020),
    'priceLabel':            Color(0xFFF472B6),
    'priceValue':            Color(0xFFFCE7F3),
    'pageIndicatorActive':   Color(0xFFFB7185),
    'pageIndicatorInactive': Color(0xFF334155),
    'iconPrimary':           Color(0xFFFB7185),
    'iconSubtle':            Color(0xFF94A3B8),
    'iconOnPrimary':         Color(0xFF1C0010),
    'iconDanger':            Color(0xFFF87171),
  };

  static final List<Map<String, dynamic>> all = [
    {'name': 'MedStockTheme', 'colors': medStock},
    {'name': 'Emerald',       'colors': emerald},
    {'name': 'Violet',        'colors': violet},
    {'name': 'Sunset',        'colors': sunset},
    {'name': 'Slate',         'colors': slate},
    {'name': 'Dark Ocean',    'colors': darkOcean},
    {'name': 'Dark Violet',   'colors': darkViolet},
    {'name': 'Dark Emerald',  'colors': darkEmerald},
    {'name': 'Dark Sunset',   'colors': darkSunset},
    {'name': 'Dark Rose',     'colors': darkRose},
  ];
}